dist: focal
language: rust
rust:
  - stable
  - nightly
before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy --all-features
  - cargo test --all-features
jobs:
  allow_failures:
    - rust: stable
