[package]
name = "microservice-utils"
version = "0.1.0-rc.2"
authors = ["Michał Pokrywka", "Vlad Ovinnikov"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
validator = "0.12"
